spring:
  application:
    name: zx-zuul
  profiles:
    active: dev
server:
  port: 8001
logging:
  config:  classpath:logback-spring.xml
#--------------------eureka-----------------------
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
#--------------------Zuul-----------------------
zuul:
  host:
    connect-timeout-millis: 6000 #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 6000   #socket超时
  #前缀
#  prefix: /api
  ignored-patterns: /**/test/**
  routes:
    zx-provider:
      #服务映射的路径，通过这路径就可以从外部访问你的服务了，目的是为了不爆露你机器的IP，面向服务的路由了，给你选一个可用的出来，
      #这里zuul是自动依赖hystrix，ribbon的，不是面向单机
      path: /zx-provider/**
      sensitiveHeaders: "*"
      #服务的名称
      serviceId: zx-provider
    zx-consumer:
      path: /zx-consumer/**
      sensitiveHeaders: "*"
      serviceId: zx-consumer
    zx-auth:
      path: /zx-auth/**
      sensitiveHeaders: "*"
      serviceId: zx-auth
  add-proxy-headers: true
#---------------------oauth2---------------------
# http://localhost:8001/zx-auth/oauth/token?grant_type=password&username=admin&password=admin&client_id=webapp&client_secret=webapp
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/zx-auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/zx-auth/oauth/authorize
      client-id: zx-auth
    resource:
      user-info-uri:  http://localhost:${server.port}/zx-auth/api/member
      prefer-token-info: false
