spring:
  application:
    name: zx-auth
  profiles:
    active: dev
  redis:
    database: 1
    port: 63179
    password: zx@!qwer
    host: 47.110.13.117
server:
  port: 8004
logging:
  config:  classpath:logback-spring.xml
#--------------------eureka-----------------------
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
