spring:
  application:
    name: zx-auth
  redis:
    database: 0
    port: 6379
    password:
server:
  port: 8004
#--------------------eureka-----------------------
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
