spring:
  application:
    name: zx-eureka
  profiles:
    active: dev
server:
  port: 8000
logging:
  config:  classpath:logback-spring.xml

eureka:
  instance:
    hostname: localhost
  client:
    #是否需要将自己注册到注册中心(注册中心集群需要设置为true)
    register-with-eureka: false
    #是否需要搜索服务信息 因为自己是注册中心所以为false
    fetch-registry: false
    #服务地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

