spring:
  application:
    name: zx-consumer
  profiles:
    active: dev
server:
  port: 8003
logging:
  config:  classpath:logback-spring.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
